spring:
  application:
    name: minioservice
server:
  port: 18003

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

#logging.level.com.shr.service.inspect.dao.inspectpoint.InspectpointResultHistoryDao: debug

